openapi: 3.0.0
info:
  title: API test
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /users/get:
    get:
      summary: testop
      tags: []
      responses: {}
      operationId: get-users-get
      description: testdesc
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                teststr:
                  type: string
            examples: {}
          application/xml:
            schema:
              type:
                - object
                - string
  /BLABLABLA:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-BLABLABLA
components:
  schemas: {}
